version: '3.1'

services:
  server:
    container_name: gateway
    image: 'node:alpine'
    working_dir: /app
    command: "npm run dev"
    volumes:
      - ./Server:/app
    ports:
      - '3789:3789'
    env_file:
      - ./Server/.env
    depends_on:
      - user_service
      - upload_service
    networks:
      - server_network
    links:
      - user_service
      - upload_service
  user_service:
    container_name: user_service
    image: 'node:alpine'
    working_dir: /app
    command: "npm run dev"
    volumes:
      - ./UserService:/app
    env_file:
      - ./UserService/.env
    networks:
      - server_network
    depends_on:
      - db_user_service
    links:
      - db_user_service
  db_user_service:
    container_name: db_user_service
    image: 'mariadb:latest'
    volumes:
      - ./UserService/db/data:/var/lib/mysql
      - ./UserService/db/sql:/docker-entrypoint-initdb.d
    env_file:
      - ./UserService/.env
    networks:
      - server_network
  upload_service:
    container_name: upload_service
    image: 'node:alpine'
    working_dir: /app
    command: "npm run dev"
    volumes:
      - ./UploadService:/app
    env_file:
      - ./UploadService/.env
    networks:
      - server_network
    depends_on:
      - db_upload_service
    links:
      - db_upload_service
  db_upload_service:
    container_name: db_upload_service
    image: 'mariadb:latest'
    volumes:
      - ./UploadService/db/data:/var/lib/mysql
      - ./UploadService/db/sql:/docker-entrypoint-initdb.d
    env_file:
      - ./UploadService/.env
    networks:
      - server_network

networks:
  server_network:
    driver: bridge